name: binaries
on:
  workflow_dispatch:

env:
  ALPINE_BRANCH: v3.18
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JOBS: 3
  LINUX_LDFLAGS: -static
jobs:
  redis-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download source code
        run: |
          $tag_name="7.2.6"
          Invoke-WebRequest -Uri https://github.com/redis/redis/archive/refs/tags/$($tag_name.Trim()).tar.gz -OutFile redis-$($tag_name.Trim()).tar.gz
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=$($tag_name.Trim())"
          Add-Content -Path $env:GITHUB_ENV -Value "REDIS_DIST=redis-$($tag_name.Trim())-win32-x86_64"

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: gcc make pkg-config libopenssl openssl-devel zip
      - name: msys2 Build Redis
        if: ${{ success() }}
        run: |
          workspace=$(pwd)
          mkdir ${{ env.REDIS_DIST }}-msys2
          sed -i 's/__GNU_VISIBLE/1/' /usr/include/dlfcn.h
          tar -xzf redis-${{ env.RELEASE_VERSION }}.tar.gz
          cd redis-${{ env.RELEASE_VERSION }}/src && ./mkreleasehdr.sh
          cd ..
          make BUILD_TLS=yes CFLAGS="-Wno-char-subscripts -O0"
          find . -mindepth 1 -maxdepth 2 -type f -regex '.*\(\.exe\|\.conf\)' -exec cp -f "{}" "$workspace/${{ env.REDIS_DIST }}" \;
          cd $workspace
          cp /usr/bin/msys-2.0.dll /usr/bin/msys-crypto-3.dll /usr/bin/msys-ssl-3.dll ${{ env.REDIS_DIST }}
          sed -i 's/pidfile \/var\/run/pidfile ./' ${{ env.REDIS_DIST }}/redis.conf
          zip -q -r ${{ env.REDIS_DIST }}-msys2.zip ${{ env.REDIS_DIST }}
          tar cvzf ${{ env.REDIS_DIST }}.tar.gz ${{ env.REDIS_DIST }}/
          mv ${{ env.REDIS_DIST }} ../artifact/${{ env.REDIS_DIST }}
        shell: msys2 {0}
  redis-multi-linux:
    name: redis-${{ matrix.REDIS_VERSION }}-linux-${{ matrix.ARCH }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        REDIS_VERSION:
          - 7.2.6
        ARCH:
          - x86_64
          - aarch64
    steps:
      - name: Download Redis
        run: wget https://github.com/redis/redis/archive/${{ matrix.REDIS_VERSION }}.tar.gz

      - name: Extract Redis
        run: tar xvzf ${{ matrix.REDIS_VERSION }}.tar.gz

      - name: Install Alpine ${{ env.ALPINE_BRANCH }} for ${{ matrix.ARCH }}
        uses: common-binaries/setup-alpine@v1
        with:
          arch: ${{ matrix.ARCH }}
          branch: ${{ env.ALPINE_BRANCH }}
          packages: >
            build-base
            linux-headers

      - name: Build Redis
        env:
          LDFLAGS: ${{ env.LINUX_LDFLAGS }}
        run: |
          mkdir artifact
          pwd
          cd redis-${{ matrix.REDIS_VERSION }}
          pwd
          make
          mkdir conf
          cp redis.conf conf/
          mkdir bin
          mv src/redis-server bin/
          BIN_NAME="redis-${{ matrix.REDIS_VERSION }}-linux-${{ matrix.ARCH }}.tar.gz"
          tar cvzf $BIN_NAME conf/ bin/
          mv $BIN_NAME ../artifact/$BIN_NAME
        shell: alpine.sh {0}

      - name: Upload redis binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: artifact/*

  upload:
    name: Upload binaries
    needs:
      - redis-multi-linux
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: docker://alpine:3.18
    steps:
      - name: Install dependencies
        run: apk add -U git

      - name: Checkout binaries branch
        uses: actions/checkout@v3
        with:
          ref: binaries
          path: binaries

      - name: Delete binaries branch
        working-directory: binaries
        run: |
          git checkout --orphan binaries_nouse
          git branch -d binaries
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git --delete binaries
          rm -fr *

      - name: Create binaries branch
        working-directory: binaries
        run: |
          git checkout --orphan binaries

      - name: Download and unpack all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: List unpacked artifact files
        run: ls -lah artifact/

      - name: Move all binaries to the repository
        run: mv -v artifact/* binaries/

      - name: Check if there are any changes
        id: has_changes
        working-directory: binaries
        run: |
          git status || exit 1
          test -n "$(git status --porcelain)" && result=yes || result=no
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: binaries
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Built from ${{ github.sha }}"

      - name: Push changes back to origin
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: binaries
        run: |
          # XXX: workaround for https://github.com/orgs/community/discussions/55820
          git config --global http.version HTTP/1.1
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git binaries
