name: binaries
on:
  workflow_dispatch:

env:
  ALPINE_BRANCH: v3.18
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JOBS: 3
  LINUX_LDFLAGS: -static
  WIN32_LDFLAGS: -Wl,--as-needed -Wl,-Map,linker.map
jobs:
  redis-multi-linux:
    name: redis-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        REDIS_VERSION:
          - 7.2.4
        ARCH:
          - x86_64
        include:
          - REDIS_VERSION: 7.2.4
    steps:
      - name: Download Redis
        run: wget https://github.com/redis/redis/archive/${{ matrix.REDIS_VERSION }}.tar.gz

      - name: Extract Redis
        run: tar xvzf ${{ matrix.REDIS_VERSION }}.tar.gz

      - name: Install Alpine ${{ env.ALPINE_BRANCH }} for ${{ matrix.ARCH }}
        uses: common-binaries/setup-alpine@v1
        with:
          arch: ${{ matrix.ARCH }}
          branch: ${{ env.ALPINE_BRANCH }}
          packages: >
            build-base
            linux-headers

      - name: Build Redis
        env:
          LDFLAGS: ${{ env.LINUX_LDFLAGS }}
        run: |
          mkdir artifact
          pwd
          cd redis-${{ matrix.REDIS_VERSION }}
          pwd
          make
          mkdir conf
          cp redis.conf conf/
          mkdir bin
          mv src/redis-server bin/
          tar cvzf redis-server-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux.tar.gz conf/ bin/
          mv redis-server-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux.tar.gz ../artifact/redis-server-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux.tar.gz
        shell: alpine.sh {0}

      - name: Upload redis binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: artifact/*

  redis-x86_64-win32:
    name: redis-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-windows
    runs-on: windows-latest
    strategy:
      matrix:
        REDIS_VERSION:
          - 7.2.4
        ARCH:
          - x86_64
    steps:
      - name: Setup MSYS2 and install packages
        uses: msys2/setup-msys2@v2
        with:
          update: false
          install: base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-jq

      - name: Download Redis
        run: wget https://github.com/redis/redis/archive/${{ matrix.REDIS_VERSION }}.tar.gz

      - name: Extract Redis
        run: tar xvzf ${{ matrix.REDIS_VERSION }}.tar.gz

      - name: Build Redis
        shell: msys2 {0}
        env:
          CFLAGS: ${{ env.CFLAGS }}
          LDFLAGS: ${{ env.WIN32_LDFLAGS }}
        run: |
          mkdir artifact
          pwd
          cd redis-${{ matrix.REDIS_VERSION }}
          pwd
          make
          mkdir conf
          cp redis.conf conf/
          mkdir bin
          mv src/redis-server bin/
          tar cvzf redis-server-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux.tar.gz conf/ bin/
          mv redis-server-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux.tar.gz ../artifact/redis-server-${{ matrix.REDIS_VERSION }}-${{ matrix.ARCH }}-linux.tar.gz        

      - name: Upload redis binary to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: artifact/*

  upload:
    name: Upload binaries
    needs:
      - redis-multi-linux
      - redis-x86_64-win32
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: docker://alpine:3.18
    steps:
      - name: Install dependencies
        run: apk add -U git

      - name: Checkout binaries branch
        uses: actions/checkout@v3
        with:
          ref: binaries
          path: binaries

      - name: Delete binaries branch
        working-directory: binaries
        run: |
          git checkout --orphan binaries_nouse
          git branch -d binaries
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git --delete binaries
          rm -fr *

      - name: Create binaries branch
        working-directory: binaries
        run: |
          git checkout --orphan binaries

      - name: Download and unpack all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: List unpacked artifact files
        run: ls -lah artifact/

      - name: Move all binaries to the repository
        run: mv -v artifact/* binaries/

      - name: Check if there are any changes
        id: has_changes
        working-directory: binaries
        run: |
          git status || exit 1
          test -n "$(git status --porcelain)" && result=yes || result=no
          echo "result=$result" >> $GITHUB_OUTPUT

      - name: Commit changes
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: binaries
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --all
          git commit -m "Built from ${{ github.sha }}"

      - name: Push changes back to origin
        if: steps.has_changes.outputs.result == 'yes'
        working-directory: binaries
        run: |
          # XXX: workaround for https://github.com/orgs/community/discussions/55820
          git config --global http.version HTTP/1.1
          git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git binaries
